sonar.projectKey=RaouiAbdelkamel_pfa-devsecops-pipeline
sonar.organization=raouiabdelkamel
sonar.projectName=PFA DevSecOps Pipeline
sonar.projectVersion=2.0
sonar.sources=app,ai-service,ai-training
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/node_modules/**
sonar.python.version=3.11
